In [32]:
import numpy as np
import cv2
from sklearn import datasets
from sklearn import model_selection
from sklearn import metrics 
from sklearn import linear_model

In [33]:
iris = datasets.load_iris()
print("Iris: {} {} {}\n{}".format(dir(iris), iris.data.shape, iris.target.shape, iris.feature_names))

Iris: ['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names'] (150, 4) (150,)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [34]:
np.unique(iris.target)

array([0, 1, 2])

In [35]:
idx = iris.target != 2

In [36]:
data = iris.data[idx].astype(np.float32)
target = iris.target[idx].astype(np.float32)
target_class = iris.target[idx].astype(np.int32)

In [37]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [38]:
from bokeh.plotting import figure, output_file, show
from bokeh.io import output_notebook
from bokeh.models import Label
output_notebook()

size = 9
p = figure(plot_width=800, plot_height=400, 
               title='Iris', 
               x_axis_label=iris.feature_names[0], y_axis_label=iris.feature_names[1])
p.circle(data[target==0, 0], data[target==0, 1], color="purple", size=size, legend="0")
p.square(data[target==1, 0], data[target==1, 1], color="firebrick", size=size, legend="1")
show(p)
    

Loading BokehJS ...

In [39]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(data, target, 
                                                                    test_size=0.1, random_state=42)

In [40]:
print("{} {} {} {} {} {}".format(data.shape, target.shape, X_train.shape, y_train.shape, 
                           X_test.shape, y_test.shape))

(100, 4) (100,) (90, 4) (90,) (10, 4) (10,)


In [41]:
log_reg = linear_model.LogisticRegression(random_state=42)

In [54]:
fitted_log_reg = log_reg.fit(X_train, y_train)

/home/ktdiedrich/.conda/envs/py36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [55]:
fitted_log_reg

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=42, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [43]:
y_train_pred = log_reg.predict(X_train)

In [44]:
y_train_pred

array([0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 1.], dtype=float32)

In [45]:
y_train

array([0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 1.], dtype=float32)

In [46]:
metrics.accuracy_score(y_train, y_train_pred)

1.0

In [47]:
y_test_pred = log_reg.predict(X_test)
metrics.accuracy_score(y_test, y_test_pred)

1.0

In [48]:
y_test_pred

array([1., 1., 1., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [49]:
y_test

array([1., 1., 1., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [50]:
X_test

array([[6. , 2.7, 5.1, 1.6],
       [5.5, 2.3, 4. , 1.3],
       [5.9, 3.2, 4.8, 1.8],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.4, 1.5, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.2]], dtype=float32)

In [51]:
print("Probability of class 0 and 1")
log_reg.predict_proba(X_test).round(2)

Probability of class 0 and 1


array([[0.  , 1.  ],
       [0.01, 0.99],
       [0.01, 0.99],
       [0.96, 0.04],
       [0.96, 0.04],
       [0.97, 0.03],
       [0.99, 0.01],
       [0.03, 0.97],
       [0.98, 0.02],
       [0.98, 0.02]])